# Generated by Django 4.2.7 on 2025-12-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Free', 'رایگان'), ('Basic', 'پلن پایه'), ('Pro', 'پرمیوم')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='templates')),
                ('description', models.TextField(blank=True)),
                ('delay', models.IntegerField()),
                ('only_for_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_plans', models.ManyToManyField(blank=True, to='Billing.userplan')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Pro', 'Pro')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('is_special', models.BooleanField()),
                ('period', models.CharField(choices=[('monthly', 'ماهانه'), ('annual', 'سالانه')], default='monthly', max_length=20)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Billing.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Features', to='Billing.plan')),
            ],
        ),
    ]
