# Generated by Django 5.2.8 on 2026-01-02 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Free', 'رایگان'), ('Basic', 'پلن پایه'), ('Pro', 'پرمیوم')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('Free', 'رایگان'), ('Basic', 'پایه'), ('Pro', 'حرفه\u200cای')], help_text='Type of subscription plan', max_length=20)),
                ('name', models.CharField(help_text='Display name of the plan', max_length=200)),
                ('price', models.PositiveIntegerField(help_text='Base price in IRR (Rials)')),
                ('is_special', models.BooleanField(default=False, help_text='Whether this is a special/recommended plan')),
                ('period', models.CharField(choices=[('monthly', 'ماهانه'), ('annual', 'سالانه')], default='monthly', help_text='Billing period for this plan', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this plan was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this plan was last updated')),
                ('discount', models.ForeignKey(blank=True, help_text='Discount applied to this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='Billing.discount')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price'],
                'unique_together': {('plan_type', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200, unique=True)),
                ('image', models.ImageField(help_text='Template preview image', upload_to='templates')),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('delay', models.PositiveIntegerField(default=0, help_text='Animation delay in milliseconds')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this template was last updated')),
                ('allowed_plans', models.ManyToManyField(blank=True, help_text='Plans that can use this template (empty = all plans)', related_name='allowed_templates', to='Billing.userplan')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the feature', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this feature was created')),
                ('plan', models.ForeignKey(help_text='Plan this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Billing.plan')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['name'],
                'unique_together': {('plan', 'name')},
            },
        ),
    ]
