# Generated by Django 5.2.8 on 2025-12-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['name'], 'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['name'], 'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.RemoveField(
            model_name='template',
            name='only_for_premium',
        ),
        migrations.AddField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, help_text='When this feature was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, help_text='When this plan was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this plan is currently available'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('Free', 'رایگان'), ('Basic', 'پایه'), ('Pro', 'حرفه\u200cای')], default=1, help_text='Type of subscription plan', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('plan_type', 'period')},
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this plan was last updated'),
        ),
        migrations.AddField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, help_text='When this template was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this template was last updated'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(help_text='Name of the feature', max_length=200),
        ),
        migrations.AlterField(
            model_name='feature',
            name='plan',
            field=models.ForeignKey(help_text='Plan this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Billing.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='Discount applied to this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='Billing.discount'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Whether this is a special/recommended plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(help_text='Display name of the plan', max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('monthly', 'ماهانه'), ('annual', 'سالانه')], default='monthly', help_text='Billing period for this plan', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(help_text='Base price in IRR (Rials)'),
        ),
        migrations.AlterField(
            model_name='template',
            name='allowed_plans',
            field=models.ManyToManyField(blank=True, help_text='Plans that can use this template (empty = all plans)', related_name='allowed_templates', to='Billing.userplan'),
        ),
        migrations.AlterField(
            model_name='template',
            name='delay',
            field=models.PositiveIntegerField(default=0, help_text='Animation delay in milliseconds'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, help_text='Template description'),
        ),
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(help_text='Template preview image', upload_to='templates'),
        ),
        migrations.AlterField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this template is available for use'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Template name', max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('plan', 'name')},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='type',
        ),
    ]
