# Generated by Django 5.2.8 on 2025-12-30 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Billing', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(blank=True, help_text='Phone number in format: 09xxxxxxxxx', max_length=11, null=True, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Optional email address', max_length=254, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, help_text="User's full name", max_length=100, null=True)),
                ('username', models.CharField(blank=True, help_text='Optional username for card URL', max_length=100, null=True, unique=True)),
                ('plan_expires_at', models.DateTimeField(blank=True, help_text='When the current plan expires', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin site')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when user joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this user was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this user was last updated')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('plan', models.ManyToManyField(blank=True, help_text="User's active subscription plans", to='Billing.userplan')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this OTP was created')),
                ('expires_at', models.DateTimeField(help_text='When this OTP expires')),
                ('user', models.ForeignKey(help_text='User this OTP belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='core_otp_user_id_e8d38d_idx'), models.Index(fields=['expires_at'], name='core_otp_expires_288351_idx')],
            },
        ),
    ]
