# Generated by Django 6.0.2 on 2026-02-25 19:54

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(db_index=True, max_length=30, unique=True, validators=[core.models.validate_subdomain_value])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subdomain', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subdomain'],
                'indexes': [models.Index(fields=['is_active', 'subdomain'], name='core_usersu_is_acti_aaf3dd_idx'), models.Index(fields=['created_at'], name='core_usersu_created_86661b_idx')],
            },
        ),
    ]
