# Generated by Django 5.2.4 on 2025-12-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xlink', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(max_length=255, unique=True)),
                ('color', models.CharField(choices=[('default', 'Default X-Link'), ('blue', 'Blue'), ('gold', 'Gold'), ('orange', 'Orange'), ('gray', 'Gray'), ('mint', 'Mint'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('green', 'Green')], default='default', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('short_bio', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('instagram_username', models.CharField(blank=True, max_length=255)),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('linkedin_username', models.CharField(blank=True, max_length=255)),
                ('youtube_username', models.CharField(blank=True, max_length=255)),
                ('twitter_username', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cards', to='Xlink.cardtemplate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.usercard')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
