# Generated by Django 5.2.4 on 2025-12-13 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Pro', 'Pro')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plan_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 10, 59, 46, 962143, tzinfo=datetime.timezone.utc)),
        ),
    ]
