# Generated by Django 6.0 on 2025-12-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='only_for_premium',
            field=models.BooleanField(default=False),
        ),
    ]
