# Generated by Django 5.2.4 on 2025-12-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plan_type_alter_customuser_plan_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Free', 'رایگان'), ('Basic', 'پرمخاطب'), ('Pro', 'پرمیوم')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='allowed_plans',
            field=models.ManyToManyField(blank=True, to='core.plan'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plan',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.ManyToManyField(to='core.userplan'),
        ),
    ]
