# Generated by Django 6.0 on 2025-12-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
