# Generated by Django 6.0 on 2025-12-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usercard_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
