# Generated by Django 5.2.4 on 2025-12-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userplan_template_allowed_plans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='allowed_plans',
            field=models.ManyToManyField(blank=True, to='core.userplan'),
        ),
    ]
