# Generated by Django 5.2.4 on 2025-12-15 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_template_allowed_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='name',
            field=models.CharField(choices=[('Free', 'رایگان'), ('Basic', 'پایه'), ('Pro', 'پرمیوم')], max_length=50),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='portfolio')),
                ('url', models.URLField(blank=True, help_text='Project URL or external link')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='core.usercard')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fas fa-code)', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.usercard')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
