# Generated by Django 6.0 on 2025-12-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='template',
            name='allowed_plans',
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Pro', 'Pro')], default='Free', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserPlan',
        ),
        migrations.AddField(
            model_name='template',
            name='allowed_plans',
            field=models.CharField(default=1, max_length=20, verbose_name=[('Free', 'Free'), ('Basic', 'Basic'), ('Pro', 'Pro')]),
            preserve_default=False,
        ),
    ]
