# Generated by Django 6.0 on 2025-12-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_customuser_plan_remove_template_allowed_plans_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Pro', 'Pro')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='template',
            name='allowed_plans',
        ),
        migrations.AddField(
            model_name='template',
            name='allowed_plans',
            field=models.ManyToManyField(blank=True, to='core.userplan'),
        ),
    ]
