# Generated by Django 5.2.4 on 2025-12-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userplan_name_portfolio_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.AddField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('monthly', 'ماهانه'), ('annual', 'سالانه')], default='monthly', max_length=20),
        ),
    ]
