# Generated by Django 6.0 on 2025-12-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='blue_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercard',
            name='stars_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
