# Generated by Django 5.2.4 on 2025-12-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_portfolio_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AlterField(
            model_name='sitecontext',
            name='footer_github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontext',
            name='footer_instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontext',
            name='footer_linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontext',
            name='footer_telegram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
