# Generated by Django 6.0 on 2025-12-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usercard_blue_tick_usercard_stars_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='black_background',
            field=models.BooleanField(default=False),
        ),
    ]
