# Generated by Django 6.0 on 2025-12-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userplan_remove_template_allowed_plans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='plan',
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.ManyToManyField(blank=True, to='core.userplan'),
        ),
    ]
