# Generated by Django 6.0 on 2025-12-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser_plan_customuser_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='value',
            field=models.CharField(choices=[('Free', 'رایگان'), ('Basic', 'پایه'), ('Pro', 'پرمیوم')], max_length=20),
        ),
    ]
