# Generated by Django 5.2.9 on 2025-12-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userplan_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='value',
            field=models.CharField(choices=[('Free', 'رایگان'), ('Basic', 'پلن پایه'), ('Pro', 'پرمیوم')], max_length=20),
        ),
    ]
