# Generated by Django 6.0 on 2025-12-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usermessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
