# Generated by Django 6.0 on 2025-12-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='show_views',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercard',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='color',
            field=models.CharField(choices=[('default', 'ایکس\u200cلینک پیش\u200cفرض'), ('blue', 'آبی'), ('gold', 'طلایی'), ('orange', 'نارنجی'), ('gray', 'خاکستری'), ('mint', 'نعنایی'), ('pink', 'صورتی'), ('purple', 'بنفش'), ('red', 'قرمز'), ('green', 'سبز')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='username',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
