# Generated by Django 6.0 on 2025-12-26 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
        ('core', '0009_customuser_updated_at_alter_userplan_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banners',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='template',
            name='allowed_plans',
        ),
        migrations.AlterField(
            model_name='usercard',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cards', to='Billing.template'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plan',
            field=models.ManyToManyField(blank=True, to='Billing.userplan'),
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='SiteContext',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='UserPlan',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
