# Generated by Django 6.0 on 2025-12-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usercard_show_views_usercard_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecontext',
            old_name='footer_linkdin_url',
            new_name='footer_linkedin_url',
        ),
    ]
