# Generated by Django 6.0 on 2025-12-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_banners_remove_plan_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user_card',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user_card',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='template',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='user',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='UserCard',
        ),
    ]
