# Generated by Django 6.0 on 2025-12-10 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_footer_linkdin_url_sitecontext_footer_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plan_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 10, 7, 2, 28, 828818, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
