# Generated by Django 6.0 on 2025-12-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
