# Generated by Django 6.0 on 2025-12-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontext',
            name='fav_icon',
            field=models.ImageField(default=1, upload_to='fav_icon'),
            preserve_default=False,
        ),
    ]
