# Generated by Django 6.0 on 2025-12-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitecontext_fav_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontext',
            name='fav_icon',
        ),
        migrations.AddField(
            model_name='sitecontext',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo'),
            preserve_default=False,
        ),
    ]
