# Generated by Django 6.0 on 2025-12-07 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('minimal', 'Minimal'), ('dark', 'Dark / Cyber'), ('neon', 'Neon / Futuristic'), ('corporate', 'Professional / Corporate'), ('gradient', 'Gradient'), ('creative', 'Creative / Modern')], max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('preview_image', models.ImageField(blank=True, upload_to='templates_images')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('customization_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='Xlink.cardtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
