# Generated by Django 6.0 on 2025-12-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xlink', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtemplate',
            name='customization_options',
        ),
        migrations.RemoveField(
            model_name='cardtemplate',
            name='style_tag',
        ),
        migrations.RemoveField(
            model_name='cardtemplate',
            name='visual_style',
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='templates_images'),
        ),
    ]
