# Generated by Django 4.2.7 on 2025-12-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='banners')),
            ],
        ),
        migrations.CreateModel(
            name='SiteContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo')),
                ('hero_section_text_part1', models.CharField(max_length=200)),
                ('hero_section_text_part2', models.CharField(max_length=200)),
                ('hero_section_text_description', models.CharField(max_length=200)),
                ('footer_section_text_part1', models.CharField(max_length=200)),
                ('footer_telegram_url', models.URLField(blank=True, null=True)),
                ('footer_linkedin_url', models.URLField(blank=True, null=True)),
                ('footer_github_url', models.URLField(blank=True, null=True)),
                ('footer_instagram_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_url', models.URLField()),
                ('company_logo', models.ImageField(upload_to='company_logo')),
                ('SiteContext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customers', to='site_management.sitecontext')),
            ],
        ),
    ]
