# Generated by Django 5.2.8 on 2025-12-30 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='banners')),
            ],
        ),
        migrations.CreateModel(
            name='SiteContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='Name of the website', max_length=100)),
                ('logo', models.ImageField(help_text='Site logo image', upload_to='logo')),
                ('hero_section_text_part1', models.CharField(help_text='First part of hero section text', max_length=200)),
                ('hero_section_text_part2', models.CharField(help_text='Second part of hero section text', max_length=200)),
                ('hero_section_text_description', models.CharField(help_text='Hero section description text', max_length=500)),
                ('footer_section_text_part1', models.CharField(help_text='Footer section text', max_length=200)),
                ('footer_telegram_url', models.URLField(blank=True, help_text='Telegram profile URL', null=True)),
                ('footer_linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('footer_github_url', models.URLField(blank=True, help_text='GitHub profile URL', null=True)),
                ('footer_instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this site context was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this site context was last updated')),
            ],
            options={
                'verbose_name': 'Site Context',
                'verbose_name_plural': 'Site Contexts',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company/customer', max_length=200)),
                ('company_url', models.URLField(help_text='Company website URL')),
                ('company_logo', models.ImageField(help_text='Company logo image', upload_to='company_logo')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this customer')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this customer was added')),
                ('site_context', models.ForeignKey(help_text='Site context this customer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='site_management.sitecontext')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['display_order', 'company_name'],
            },
        ),
    ]
