# Generated by Django 6.0.2 on 2026-02-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this customer is marked as test data'),
        ),
    ]
