# Generated by Django 5.2.8 on 2025-12-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0002_banners_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='image',
        ),
    ]
