# Generated by Django 5.2.8 on 2025-12-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0003_remove_banners_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
