# Generated by Django 5.2.8 on 2025-12-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0004_banners_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company_logo',
        ),
    ]
