# Generated by Django 5.2.9 on 2026-01-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='portfolio')),
                ('url', models.URLField(blank=True, help_text='Project URL or external link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Items',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name displayed on card', max_length=255)),
                ('username', models.SlugField(help_text='Unique URL slug for the card', max_length=32, unique=True)),
                ('profile_picture', models.ImageField(help_text='Profile picture for the card', upload_to='profile_pics')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number to display', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email address to display', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Personal website URL')),
                ('short_bio', models.CharField(blank=True, help_text='Short biography/tagline', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description/about section')),
                ('instagram_username', models.CharField(blank=True, help_text='Instagram username', max_length=255)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram username', max_length=255)),
                ('linkedin_username', models.CharField(blank=True, help_text='LinkedIn username', max_length=255)),
                ('youtube_username', models.CharField(blank=True, help_text='YouTube channel username', max_length=255)),
                ('twitter_username', models.CharField(blank=True, help_text='Twitter/X username', max_length=255)),
                ('github_username', models.CharField(blank=True, help_text='GitHub username', max_length=255)),
                ('color', models.CharField(choices=[('default', 'ایکس\u200cلینک پیش\u200cفرض'), ('gold', 'طلایی'), ('orange', 'نارنجی'), ('gray', 'خاکستری'), ('mint', 'نعنایی'), ('pink', 'صورتی'), ('purple', 'بنفش'), ('red', 'قرمز'), ('green', 'سبز')], default='default', help_text='Card color theme', max_length=20)),
                ('blue_tick', models.BooleanField(default=False, help_text='Show blue verification tick')),
                ('stars_background', models.BooleanField(default=False, help_text='Show animated stars background')),
                ('black_background', models.BooleanField(default=False, help_text='Use black background theme')),
                ('views', models.PositiveIntegerField(default=0, help_text='Number of times card was viewed')),
                ('show_views', models.BooleanField(default=False, help_text='Whether to display view count on card')),
                ('is_published', models.BooleanField(default=True, help_text='Whether card is publicly accessible')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this card was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this card was last updated')),
                ('template', models.ForeignKey(blank=True, help_text='Card template/styling', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cards', to='Billing.template')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
