# Generated by Django 4.2.7 on 2025-12-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='portfolio')),
                ('url', models.URLField(blank=True, help_text='Project URL or external link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Items',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_tick', models.BooleanField(default=False)),
                ('stars_background', models.BooleanField(default=False)),
                ('black_background', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('show_views', models.BooleanField(default=False)),
                ('username', models.SlugField(max_length=32, unique=True)),
                ('profile_picture', models.ImageField(upload_to='profile_pics')),
                ('color', models.CharField(choices=[('default', 'ایکس\u200cلینک پیش\u200cفرض'), ('gold', 'طلایی'), ('orange', 'نارنجی'), ('gray', 'خاکستری'), ('mint', 'نعنایی'), ('pink', 'صورتی'), ('purple', 'بنفش'), ('red', 'قرمز'), ('green', 'سبز')], default='default', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('short_bio', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('instagram_username', models.CharField(blank=True, max_length=255)),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('linkedin_username', models.CharField(blank=True, max_length=255)),
                ('youtube_username', models.CharField(blank=True, max_length=255)),
                ('twitter_username', models.CharField(blank=True, max_length=255)),
                ('github_username', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cards', to='Billing.template')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
