# Generated by Django 5.2.8 on 2025-12-30 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='user',
            field=models.OneToOneField(help_text='User who owns this card', on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cards.usercard'),
        ),
        migrations.AddField(
            model_name='service',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='cards.usercard'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='cards.usercard'),
        ),
        migrations.AddIndex(
            model_name='usercard',
            index=models.Index(fields=['username'], name='cards_userc_usernam_8da1db_idx'),
        ),
        migrations.AddIndex(
            model_name='usercard',
            index=models.Index(fields=['is_published', 'username'], name='cards_userc_is_publ_f2de3c_idx'),
        ),
        migrations.AddIndex(
            model_name='usercard',
            index=models.Index(fields=['user'], name='cards_userc_user_id_0bb36f_idx'),
        ),
    ]
