# Generated by Django 4.2.7 on 2025-12-28 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cards.usercard'),
        ),
        migrations.AddField(
            model_name='service',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='cards.usercard'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='cards.usercard'),
        ),
    ]
