# Generated by Django 5.2.8 on 2025-12-29 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
        ('cards', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='black_background',
            field=models.BooleanField(default=False, help_text='Use black background theme'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='blue_tick',
            field=models.BooleanField(default=False, help_text='Show blue verification tick'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='color',
            field=models.CharField(choices=[('default', 'ایکس\u200cلینک پیش\u200cفرض'), ('gold', 'طلایی'), ('orange', 'نارنجی'), ('gray', 'خاکستری'), ('mint', 'نعنایی'), ('pink', 'صورتی'), ('purple', 'بنفش'), ('red', 'قرمز'), ('green', 'سبز')], default='default', help_text='Card color theme', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this card was created'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description/about section'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address to display', max_length=254),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='github_username',
            field=models.CharField(blank=True, help_text='GitHub username', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='Instagram username', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether card is publicly accessible'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='linkedin_username',
            field=models.CharField(blank=True, help_text='LinkedIn username', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='name',
            field=models.CharField(help_text='Full name displayed on card', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number to display', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='profile_picture',
            field=models.ImageField(help_text='Profile picture for the card', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='short_bio',
            field=models.CharField(blank=True, help_text='Short biography/tagline', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='show_views',
            field=models.BooleanField(default=False, help_text='Whether to display view count on card'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='stars_background',
            field=models.BooleanField(default=False, help_text='Show animated stars background'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Card template/styling', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cards', to='Billing.template'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='twitter_username',
            field=models.CharField(blank=True, help_text='Twitter/X username', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this card was last updated'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='user',
            field=models.OneToOneField(help_text='User who owns this card', on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='username',
            field=models.SlugField(help_text='Unique URL slug for the card', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times card was viewed'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='website',
            field=models.URLField(blank=True, help_text='Personal website URL'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='youtube_username',
            field=models.CharField(blank=True, help_text='YouTube channel username', max_length=255),
        ),
        migrations.AddIndex(
            model_name='usercard',
            index=models.Index(fields=['username'], name='cards_userc_usernam_8da1db_idx'),
        ),
        migrations.AddIndex(
            model_name='usercard',
            index=models.Index(fields=['is_published', 'username'], name='cards_userc_is_publ_f2de3c_idx'),
        ),
        migrations.AddIndex(
            model_name='usercard',
            index=models.Index(fields=['user'], name='cards_userc_user_id_0bb36f_idx'),
        ),
    ]
